name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
    - run: npm run build
    - uses: actions/deploy-pages@v1
      with:
        artifact_name: github-pages
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: tar -czf github-pages.tar.gz dist/
    - uses: actions/upload-pages-artifact@v1
      with:
        path: dist/
